### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by ImmanuelSamuel** [Muffasa/ionic2-meteor-starter#1]
I get the following errors.

ERROR in [default] /media/j/PTLJ/Projects/BuddyApp/ionic2-meteor-starter/app/collections/parties.ts:1:20 
Cannot find module 'angular2-meteor-client'

ERROR in [default] /media/j/PTLJ/Projects/BuddyApp/ionic2-meteor-starter/app/pages/page2/page2.ts:5:30 
Cannot find module 'angular2-meteor-client'.

ERROR in [default] /media/j/PTLJ/Projects/BuddyApp/ionic2-meteor-starter/app/pages/page2/page2.ts:15:12 
Cannot find namespace 'Mongo'.

I used to get the same for the MeteorApp but I changed the path from 'ionic2-meteor'  to 'ionic2-meteor/dist/meteor_app'. Is this just an import issue because of the path. How come it works for you but not for unless I give the actual js file name

**Comment by ohadgk** [comment]
Those are typings errors they shouldn't break the transpile. After running ionic serve what you get on http://localhost:8100? Ill push new commit with a typings directory soon.

**Comment by ImmanuelSamuel** [comment]
I am getting the page. The previous errors are gone now.
Now I see `Cannot find namespace 'core'.`
Also when I do Parties.insert in page1.ts it is getting inserted twice. Is it because it is being run both on client and server?

**Comment by ohadgk** [comment]
You must manipulate the Parties collection only within a class that expands MeteorComponent.
in this starter its page2.
